# List of hosts running cadvisor                                                                                                                                                                                                                                                                        

# List of hosts running substrate    
global:
  scrape_interval:     15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

scrape_configs:

  - job_name: 'prometheus'
    static_configs:
    - targets: ['localhost:9090']

  - job_name: 'cadvisor'
    static_configs:
    - targets: [cadvisor:8080]

  - job_name: 'node_exporter'
    static_configs:
    - targets: [node_exporter:9100]

  - job_name: 'polkadot_node'
    static_configs:
    - targets: [polkadot:9615]


    