{
 "title": "Polkadot metrics custom",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "Grandpa", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Block Height",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "substrate_block_height" }
   ]
  },
  {
   "title": "Precommits",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 7, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "substrate_finality_grandpa_precommits_total"
    }
   ]
  },
  {
   "title": "Prevots rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 14, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(substrate_finality_grandpa_prevotes_total[5m])"
    }
   ]
  },
  { "title": "Authority Discovery", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "External Addresses Last Published",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "substrate_authority_discovery_amount_external_addresses_last_published"
    }
   ]
  },
  {
   "title": "Address Requests Pending",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 7, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "substrate_authority_discovery_authority_address_requests_pending  "
    }
   ]
  },
  {
   "title": "Address Requests Total",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 14, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(substrate_authority_discovery_authority_addresses_requested_total  [5m])"
    }
   ]
  },
  {
   "title": "known authorities count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "substrate_authority_discovery_known_authorities_count  "
    }
   ]
  },
  {
   "title": "known authorities count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 7, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "substrate_authority_discovery_known_authorities_count  "
    }
   ]
  },
  {
   "title": "Handle value found event failure",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 14, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(substrate_authority_discovery_handle_value_found_event_failure[5m])"
    }
   ]
  },
  {
   "title": "time published total",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(substrate_authority_discovery_times_published_total  [5m])"
    }
   ]
  },
  {
   "title": "p2p",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 },
   "collapsed": true,
   "panels": [
    {
     "title": "conn_open",
     "type": "graph",
     "gridPos": { "h": 7, "w": 5, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "substrate_sub_libp2p_connections_opened_total"
      }
     ]
    },
    {
     "title": "peer conn closed",
     "type": "graph",
     "gridPos": { "h": 7, "w": 5, "x": 5, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "substrate_sub_libp2p_distinct_peers_connections_closed_total"
      }
     ]
    },
    {
     "title": "kademlia random queries",
     "type": "graph",
     "gridPos": { "h": 7, "w": 5, "x": 10, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "substrate_sub_libp2p_kademlia_random_queries_total"
      }
     ]
    },
    {
     "title": "kademlia record count",
     "type": "graph",
     "gridPos": { "h": 7, "w": 5, "x": 15, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "substrate_sub_libp2p_kademlia_records_count"
      }
     ]
    },
    {
     "title": "peer conn open",
     "type": "graph",
     "gridPos": { "h": 8, "w": 5, "x": 0, "y": 8 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "substrate_sub_libp2p_connections_opened_total"
      }
     ]
    },
    {
     "title": "conn_closed",
     "type": "graph",
     "gridPos": { "h": 8, "w": 5, "x": 5, "y": 8 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "substrate_sub_libp2p_connections_closed_total"
      }
     ]
    },
    {
     "title": "listener errors",
     "type": "graph",
     "gridPos": { "h": 7, "w": 5, "x": 15, "y": 8 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "substrate_sub_libp2p_listeners_errors_total"
      }
     ]
    },
    {
     "title": "incoming connections",
     "type": "graph",
     "gridPos": { "h": 8, "w": 5, "x": 0, "y": 16 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "substrate_sub_libp2p_incoming_connections_total"
      }
     ]
    },
    {
     "title": "is major syncing",
     "type": "graph",
     "gridPos": { "h": 8, "w": 5, "x": 5, "y": 16 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "substrate_sub_libp2p_is_major_syncing"
      }
     ]
    }
   ]
  },
  {
   "title": "Gossip expired message total",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(substrate_network_gossip_expired_messages_total[5m])"
    }
   ]
  },
  {
   "title": "Gossip expired message total",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 7, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(substrate_network_gossip_expired_messages_total[5m])"
    }
   ]
  },
  {
   "title": "Process start time in seconds",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 14, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "substrate_process_start_time_seconds"
    }
   ]
  },
  {
   "title": "Proposer: Number of transactions",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 43 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "substrate_proposer_number_of_transactions"
    }
   ]
  },
  {
   "title": "Ready transaction number",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 7, "y": 43 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "substrate_ready_transactions_number"
    }
   ]
  },
  {
   "title": "State Cache bytes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 14, "y": 43 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "substrate_state_cache_bytes" }
   ]
  },
  {
   "title": "Txpool: Tx pruned",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 51 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "substrate_sub_txpool_block_transactions_pruned"
    }
   ]
  },
  {
   "title": "Txpool: Submitted txns",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 7, "y": 51 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "substrate_sub_txpool_submitted_transactions"
    }
   ]
  },
  {
   "title": "Txpool: Validations finished",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 14, "y": 51 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "substrate_sub_txpool_validations_finished"
    }
   ]
  },
  {
   "title": "Proposer: Block constructed Bucket",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 59 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "substrate_proposer_block_constructed_bucket"
    }
   ]
  },
  {
   "title": "Txpool: Validations Scheduled",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 7, "y": 59 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "substrate_sub_txpool_validations_scheduled"
    }
   ]
  },
  {
   "title": "Txpool: Validations Invalid",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 14, "y": 59 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "substrate_sub_txpool_validations_invalid"
    }
   ]
  },
  {
   "title": "Sync: Propagated Txns",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 67 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "substrate_sync_propagated_transactions"
    }
   ]
  },
  {
   "title": "Tasks: total ended",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 7, "y": 67 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(substrate_tasks_ended_total[5m])"
    }
   ]
  },
  {
   "title": "Tasks: Polling duration bucket",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 14, "y": 67 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(substrate_tasks_polling_duration_bucket[5m])) by (le))"
    }
   ]
  },
  {
   "title": "Sync: Peers",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 75 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "substrate_sync_peers" }
   ]
  },
  {
   "title": "Tasks: Polling duration count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 7, "y": 75 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "substrate_tasks_polling_duration_count"
    }
   ]
  },
  {
   "title": "Tasks: Polling started total",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 14, "y": 75 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(substrate_tasks_polling_started_total[5m])"
    }
   ]
  },
  {
   "title": "Tasks: Spawned total",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 83 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "substrate_tasks_spawned_total" }
   ]
  },
  {
   "title": "Tokio threads total",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 7, "y": 83 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "substrate_tokio_threads_total" }
   ]
  },
  {
   "title": "Tokio threads alive",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 14, "y": 83 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "substrate_tokio_threads_alive" }
   ]
  },
  {
   "title": "Unbounded CHannel length",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 91 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "substrate_unbounded_channel_len"
    }
   ]
  },
  {
   "title": "Process: CPU seconds rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 7, "y": 91 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total[5m])"
    }
   ]
  },
  {
   "title": "Process: fds Max",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 14, "y": 91 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "process_max_fds" }
   ]
  },
  {
   "title": "Process: fds Open",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 99 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "process_open_fds" }
   ]
  },
  {
   "title": "Process: Resident Memory Bytes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 7, "y": 99 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "process_resident_memory_bytes" }
   ]
  },
  {
   "title": "Process: Start Time Seconds",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 14, "y": 99 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "substrate_process_start_time_seconds"
    }
   ]
  },
  {
   "title": "Process: Virtual Memory Max Bytes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 107 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "process_virtual_memory_max_bytes"
    }
   ]
  },
  {
   "title": "Process: Virtual Memory Bytes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 7, "y": 107 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "process_virtual_memory_bytes" }
   ]
  }
 ]
}